project:
  type: website
  output-dir: docs

website:
  title: "Bhaskar Kumawat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - fun.qmd
      - generate_grid_data.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



